services:
  storage-service:
    build: .
    container_name: storage-service
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_REDIS_HOST=redis-container
      - SPRING_REDIS_PORT=6379
      - B2_TOKEN_TTL_SECONDS=518400 #desired TTL
    networks:
      - app-network
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - app-network

volumes:
  redis-data:

networks:
  app-network:
    driver: bridge
