services:
  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - app-network
volumes:
  redis-data:
networks:
  app-network:
    driver: bridge